name: ucad_parki
description: "App de parqueo universitario UCAD."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/parky.png
    - assets/avatar1.png
    - assets/avatar2.png
    - assets/avatar3.png
    - assets/avatar4.png